site_name: BSB-LAN
theme: mkdocs
site_url: https://docs.bsb-lan.de
use_directory_urls: false

extra_css:
  - style.css

markdown_extensions:
  - attr_list
  - pymdownx.snippets

plugins:
  - search
#  - with-pdf
  - autorefs
  - i18n:
      reconfigure_search: true
      docs_structure: folder
      languages:
          - locale: en
            name: English
            build: true
            default: true
          - locale: de
            name: Deutsch
            build: true
            nav_translations:
                Overview: Überblick
                Quickstart: Schnellstart
                How it works: Wie funktioniert's?
                Supported Heating Systems: Unterstützte Heizungssysteme
                The BSB-LAN Adapter: Der BSB-LAN Adapter
                The BSB/LPB/PPS Bus: Der BSB/LPB/PPS Bus
                How to set it up: Installation
                Installation: Zusammenbauen
                Configuration: Konfiguration
                ChangeLog: ChangeLog
                How to use it: Was kann es?
                BSB-LAN's functions: BSB-LAN Funktionen
                Connect to your Smart Home: Mit dem Smart Home verbinden
                Help!: Hilfe!
                Troubleshooting: Fehlersuche
                FAQ: FAQ
                Wiki: Wiki
                YouTube Tutorials: YouTube Tutorials
          - locale: fr
            name: Français
            build: true
            nav_translations:
                Overview: Aperçu
                Quickstart: Démarrage rapide
                How it works: Comment ça marche?
                Supported Heating Systems: Systèmes de chauffage pris en charge
                The BSB-LAN Adapter: L'adaptateur BSB-LAN
                The BSB/LPB/PPS Bus: Les BSB/LPB/PS bus
                How to set it up: Installer
                Installation: Assemblage
                Configuration: Configuration
                ChangeLog: ChangeLog
                How to use it: Utiliser
                BSB-LAN's functions: Fonctionnes de BSB-LAN
                Connect to your Smart Home: Connecter à la Smart Home
                Help!: Au secours!
                Troubleshooting: Dépannage
                FAQ: FAQ
                Wiki: Wiki
                YouTube Tutorials: YouTube tutoriels

nav:
  - Overview: README.md
  - Quickstart: quickstart.md
  - How it works:
    - Supported Heating Systems: supported_heating_systems.md
    - The BSB-LAN Adapter: bsb-lan_adapter.md
    - The BSB/LPB/PPS Bus: bus_systems.md
  - How to set it up:
    - Installation: install.md
    - Configuration: configure.md
    - ChangeLog: CHANGELOG.md
  - How to use it:
    - BSB-LAN's functions: using.md
    - Connect to your Smart Home: homeautomation.md
  - Help!:
    - Troubleshooting: troubleshooting.md
    - FAQ: faq.md
    - Wiki: "https://github.com/fredlcore/BSB-LAN/wiki"
    - YouTube Tutorials: "https://www.youtube.com/@BSB-LAN"
  - 🌐:
    - Deutsch: /de/
    - English: /
    - Français: /fr/
