name: PlatformIO CI ESP32

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
        - "3.8"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio
        key: ${{ runner.os }}-python${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade platformio
        platformio update

        # Ethernet library
        platformio lib -g install 872

    - name: Setup config
      run: |
        cp BSB_LAN/BSB_LAN_config.h.default BSB_LAN/BSB_LAN_config.h
        cp BSB_LAN/BSB_LAN_custom_defs.h.default BSB_LAN/BSB_LAN_custom_defs.h

    - name: Run PlatformIO CI
      run: platformio ci --project-option="board_build.partitions = min_spiffs.csv" --project-option="platform = https://github.com/platformio/platform-espressif32.git" --project-option="platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.1, framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.1/esp32-arduino-libs-3.0.1.zip" --board=esp32-evb ./BSB_LAN
